### PR TITLE
Skip setting state-is-nonnegative in set_model_settings for models wi…

### PR DESCRIPTION
**Pull request by dweindl**
…th conservation laws

Until #1649 is addressed in some other way.

### CODE REVIEW

**Review by dilpath — APPROVED** [review]
Could add a warning, in case a user tries to manually set it with this method? Then there may be one warning per start of a multi-start optimization in pyPESTO.

**Comment by dweindl** [comment]
> Could add a warning, in case a user tries to manually set it with this method? Then there may be one warning per start of a multi-start optimization in pyPESTO.

I think that would rather confuse people. I don't think the method is really convenient to use in any scenario other than `get_model_settings` -> `set_model_settings`.

**Review by FFroehlich — COMMENTED** [review]
Why is this not handled by
```
    auto any_state_non_negative = std::any_of(nonNegative.begin(),
                                              nonNegative.end(),
                                              [](bool x) { return x; });
```
? If there are conservation laws, shouldn't all the stored values be set to False?

**Comment by dweindl** [comment]
> Why is this not handled by
> 
> ```
>     auto any_state_non_negative = std::any_of(nonNegative.begin(),
>                                               nonNegative.end(),
>                                               [](bool x) { return x; });
> ```
> 
> ? If there are conservation laws, shouldn't all the stored values be set to False?

Good question.

**Comment by dweindl** [comment]
Better addressed by #1738

**Pull request closed without merging**
