### PR TITLE
Workaround for PEtab problems with state-dependent noise models

### PR DESCRIPTION
**Pull request by dweindl**
PEtab does currently not allow observables in noiseFormula and AMICI cannot handle states in sigma expressions. Therefore, where possible, replace species occurring in the error model definition by observableIds.

See also #1788

### CODE REVIEW

**Review by FFroehlich — APPROVED** [review]
test with` Raia_CancerResearch2011` bechmark model? if gradients don't match for that model just ignore?

**Comment by FFroehlich** [comment]
> test with` Raia_CancerResearch2011` bechmark model? if gradients don't match for that model just ignore failure?

**Comment by FFroehlich** [comment]
> test with` Raia_CancerResearch2011` bechmark model? if llh value doesn't match just ignore for that model?

**Comment by dweindl** [comment]
> test with` Raia_CancerResearch2011` bechmark model? if gradients don't match for that model just ignore?

In its [current](https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/commit/4bc0af9b142c73f9cce57f7899e511f0f53492ab) form, that one uses observables in `noiseFormula`, not states. So not a good test case (yet).

**Pull request merged**
