### PR TITLE
Switch the default steady-state sensitivity method to simulationFSA.

### PR DESCRIPTION
**Pull request by stephanmg**
Changing the default steady-state sensitivity method to `simulationFSA` might increase the computation time but on the other hand be more robust across benchmark models.

### CODE REVIEW

**Review by paulstapor — APPROVED** [review]

**Comment by dweindl** [comment]
That may break existing applications (using adjoint sensitivities), right?

**Comment by dweindl** [comment]
> That may break existing applications (using adjoint sensitivities), right?

Ah, no, I think it shouldn't. But it may lead to surprisingly long simulation times for people relying on the current defaults?

Please include a few words on the rationale for the change and potential additional (undesired) consequences in the PR description.

**Comment by paulstapor** [comment]
> Please include a few words on the rationale for the change and potential additional (undesired) consequences in the PR description.

hm... I think in those cases, where it's currently used, it will rather lead to AMICI throwing an error, since the new default can't be combined with adjoints. Hence, one will have to set it to newtonOnly by hand. However, There would be a good way around, which is however slightly more complex than a one-liner...
(Can outline it, if helpful...)

**Comment by dweindl** [comment]
> I think in those cases, where it's currently used, it will rather lead to AMICI throwing an error, since the new default can't be combined with adjoints

Hm. Does it then really solve more problems than it creates?

**Comment by FFroehlich** [comment]
> > I think in those cases, where it's currently used, it will rather lead to AMICI throwing an error, since the new default can't be combined with adjoints
> 
> Hm. Does it then really solve more problems than it creates?

Agreed, I think fixing https://github.com/AMICI-dev/AMICI/issues/672 would be the better approach and shouldn't require too much effort.

**Comment by paulstapor** [comment]
> Hm. Does it then really solve more problems than it creates?

Afaik, it only affects the CanPathPro related things... Because models, which have a looong runtime and where you can't use the simulationFSA mode but really *must* use adjoints: That's atm exclusively CanPathPro... However, chaging that default to something more stable would help quite some people I think...

**Comment by dweindl** [comment]
> Afaik, it only affects the CanPathPro related things... Because models, which have a looong runtime and where you can't use the simulationFSA mode but really _must_ use adjoints: That's atm exclusively CanPathPro...

If it will break stuff for everybody using preequilibration with adjoints and unset steadystate sensitivity mode, it doesn't really matter whether or not adjoints are "required" for the given application.

I vote for leaving it as it is, as I don't see a big enough advantage, but I don't feel too strong about it.

**Comment by stephanmg** [comment]
So shall we close this issue as `invalid` in favor of issue #672?

**Comment by stephanmg** [comment]
Closed for now in favor of another issue #672.

**Pull request closed without merging**
