### PR TITLE
Add stacklevel to warnings

### PR DESCRIPTION
**Pull request by dweindl**
Make it easier to find out where warnings originate from.

### CODE REVIEW

**Comment by FFroehlich** [comment]
Hmm, is it not possible to manage this using a context manager? Seems rather difficult to keep stack levels cohesive throughout the package.

**Comment by dweindl** [comment]
> Hmm, is it not possible to manage this using a context manager? Seems rather difficult to keep stack levels cohesive throughout the package.

Finding the precise frame / code location where some deprecated argument is introduced is overkill in my opinion.

For the module-level deprecation warnings level=2 always makes sense, because this will show the location of the deprecated import statement.

**Comment by FFroehlich** [comment]
> > Hmm, is it not possible to manage this using a context manager? Seems rather difficult to keep stack levels cohesive throughout the package.
> 
> Finding the precise frame / code location where some deprecated argument is introduced is overkill in my opinion.
> 
> For the module-level deprecation warnings, `stacklevel=2` always makes sense, because this will show the location of the deprecated import statement.

Yes, my concern is more that the next time we add a warning, we will forget to add the `stacklevel=2` argument.

**Comment by dweindl** [comment]
> my concern is more that the next time we add a warning, we will forget to add the `stacklevel=2` argument.

Oh, no worries, I'm happy to add a reminder: https://docs.astral.sh/ruff/rules/no-explicit-stacklevel/

**Review by FFroehlich — APPROVED** [review]

**Pull request merged**
