### PR TITLE
GHA: test python3.12

### PR DESCRIPTION
**Pull request by dweindl**
Run nightly tests also on python3.12

Waiting for 
- [x] #2180 
- [ ] sympy 1.12.1 / 1.13.0

### CODE REVIEW

**Comment by dweindl** [comment]
@FFroehlich Can you please rebase https://github.com/FFroehlich/pysb/tree/fix_pattern_matching onto the latest pysb? In the current state it's not installable with python3.12.

<details><summary>Details</summary>
<p>

```
Collecting git+https://github.com/FFroehlich/pysb@fix_pattern_matching
  Cloning https://github.com/FFroehlich/pysb (to revision fix_pattern_matching) to /tmp/pip-req-build-5o91yuil
  Running command git clone --filter=blob:none --quiet https://github.com/FFroehlich/pysb /tmp/pip-req-build-5o91yuil
  Running command git checkout -b fix_pattern_matching --track origin/fix_pattern_matching
  Switched to a new branch 'fix_pattern_matching'
  branch 'fix_pattern_matching' set up to track 'origin/fix_pattern_matching'.
  Resolved https://github.com/FFroehlich/pysb to commit c400f1c49fc2f59b153b64e0a86e0e6886bedb41
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      /tmp/pip-req-build-5o91yuil/versioneer.py:467: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-5o91yuil/setup.py", line 53, in <module>
          main()
        File "/tmp/pip-req-build-5o91yuil/setup.py", line 16, in main
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-req-build-5o91yuil/versioneer.py", line 1405, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-req-build-5o91yuil/versioneer.py", line 1339, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-req-build-5o91yuil/versioneer.py", line 399, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
```

</p>
</details>

**Comment by FFroehlich** [comment]
done, also bumping up getting that branch merged on my todo list

**Comment by dweindl** [comment]
Generally works. Some sympy `DeprecationWarning`s, one of them causing a `BnglImportError` 

```
FAILED python/tests/test_bngl.py::test_compare_to_pysb_simulation[CaOscillate_Func] - DeprecationWarning: ast.NameConstant is deprecated and will be removed in Python 3.14; use ast.Constant instead
FAILED python/tests/test_bngl.py::test_compare_to_pysb_simulation[gene_expr] - DeprecationWarning: ast.NameConstant is deprecated and will be removed in Python 3.14; use ast.Constant instead
FAILED python/tests/test_bngl.py::test_compare_to_pysb_simulation[gene_expr_func] - DeprecationWarning: ast.NameConstant is deprecated and will be removed in Python 3.14; use ast.Constant instead
FAILED python/tests/test_bngl.py::test_compare_to_pysb_simulation[gene_expr_simple] - DeprecationWarning: ast.NameConstant is deprecated and will be removed in Python 3.14; use ast.Constant instead
FAILED python/tests/test_bngl.py::test_compare_to_pysb_simulation[Motivating_example_cBNGL] - DeprecationWarning: ast.NameConstant is deprecated and will be removed in Python 3.14; use ast.Constant instead
FAILED python/tests/test_bngl.py::test_compare_to_pysb_simulation[motor] - pysb.importers.bngl.BnglImportError: Could not parse expression kPlus:  w*exp(((g1/2.0)*((1.0/2.0)-((CheYp/((cellVolume*_Na)*(10^-6)))/(Kd+(CheYp/((cellVolume*_Na)*(10^-6)))))))) 

Error: ast.NameConstant is deprecated and will be removed in Python 3.14; use ast.Constant instead
FAILED python/tests/test_bngl.py::test_compare_to_pysb_simulation[test_setconc] - DeprecationWarning: ast.Num is deprecated and will be removed in Python 3.14; use ast.Constant instead
FAILED python/tests/test_bngl.py::test_compare_to_pysb_simulation[Repressilator] - DeprecationWarning: ast.NameConstant is deprecated and will be removed in Python 3.14; use ast.Constant instead
FAILED python/tests/test_bngl.py::test_compare_to_pysb_simulation[test_paramname] - DeprecationWarning: ast.NameConstant is deprecated and will be removed in Python 3.14; use ast.Constant instead
FAILED python/tests/test_pysb.py::test_compare_to_pysb_simulation[localfunc] - DeprecationWarning: ast.NameConstant is deprecated and will be removed in Python 3.14; use ast.Constant instead
FAILED python/tests/test_pysb.py::test_energy - DeprecationWarning: ast.NameConstant is deprecated and will be removed in Python 3.14; use ast.Constant instead
FAILED python/tests/test_splines_short.py::test_spline_piecewise - DeprecationWarning: ast.Num is deprecated and will be removed in Python 3.14; use ast.Constant instead
FAILED python/tests/test_splines_short.py::test_two_splines - DeprecationWarning: ast.Num is deprecated and will be removed in Python 3.14; use ast.Constant instead
FAILED python/tests/test_splines_short.py::test_splines_plist - DeprecationWarning: ast.Num is deprecated and will be removed in Python 3.14; use ast.Constant instead
```

**Comment by dweindl** [comment]
PySB is currently restricts sympy to <1.12 https://github.com/pysb/pysb/commit/e83937cb8c74afc9b2fa96595b68464946745f33

**Comment by dweindl** [comment]
works with sympy@master https://github.com/AMICI-dev/AMICI/actions/runs/7214927173/job/19658093049

**Review by FFroehlich — APPROVED** [review]
👍

**Pull request merged**
