### PR TITLE
Fix resetting ReturnData::numstepsB when re-using Solver

### PR DESCRIPTION
**Pull request by dweindl**
So far only a test case demonstrating #1813.

### CODE REVIEW

**Review by FFroehlich — APPROVED** [review]

**Comment by FFroehlich** [comment]
sounds like numsteps is also not properly ordered in some cases?

**Comment by dweindl** [comment]
> sounds like numsteps is also not properly ordered in some cases?

The last one seems to be 0 sometimes :thinking:

**Comment by dweindl** [comment]
> > sounds like numsteps is also not properly ordered in some cases?
> 
> The last one seems to be 0 sometimes thinking

Ah, for t=inf it should just copy the previous value, as it's supposed to be the cumulative sum.

**Comment by FFroehlich** [comment]
> > > sounds like numsteps is also not properly ordered in some cases?
> > 
> > 
> > The last one seems to be 0 sometimes thinking
> 
> Ah, for t=inf it should just copy the previous value, as it's supposed to be the cumulative sum.

would keep the numbers as is, as otherwise we would also have to carry over numbers from pre-equilibration and it's probably less confusing if these values are kept seperate.

**Comment by dweindl** [comment]
> would keep the numbers as is, as otherwise we would also have to carry over numbers from pre-equilibration and it's probably less confusing if these values are kept separate.

Ok. Could consider changing from cumulative sum to deltas, at some point...

**Pull request merged**
