### PR TITLE
Bugfix for piecewise functions

### PR DESCRIPTION
**Pull request by lcontento**
* If a piecewise function has conditions using logical operators and is found inside a SBML assignment rule, then logical operators must be parsed before each sympification.
* Makes MathML printing of `sympy.Float` round-trippable (can be removed if https://github.com/sympy/sympy/pull/19958 is accepted). However, libSBML will truncate floats anyway, so the Sympy -> SBML -> Sympy round-trip cannot be achieved...

### CODE REVIEW

**Comment by FFroehlich** [comment]
Not sure whats wrong here, need to investigate why tests aren't starting as expected.

**Comment by FFroehlich** [comment]
Okay looks like dockerhub deployment doesn't work from forks as secrets are not available. Kinda makes sense. @dweindl How do you feel about only pushing to dockerhub on release?

**Comment by FFroehlich** [comment]
> Okay looks like dockerhub deployment doesn't work from forks as secrets are not available. Kinda makes sense. @dweindl How do you feel about only pushing to dockerhub on master/develop?

**Comment by dweindl** [comment]
> Okay looks like dockerhub deployment doesn't work from forks as secrets are not available. Kinda makes sense. @dweindl How do you feel about only pushing to dockerhub on master/develop?

Works for me. Not sure if even used by anybody...
If needed on other branches in the future, this can probably be set up to ignore forks.

**Pull request merged**
