### PR TITLE
Release 0.12.0

### PR DESCRIPTION
**Pull request by dweindl**

### CODE REVIEW

**Comment by FFroehlich** [comment]
Would argue that with the addition of event observables, we should bump the version number to `0.12.0`.

**Comment by dweindl** [comment]
> Would argue that with the addition of event observables, we should bump the version number to `0.12.0`.

Fine with me. Wasn't done very consistently so far... Should do on any new feature...

**Comment by FFroehlich** [comment]
> > Would argue that with the addition of event observables, we should bump the version number to `0.12.0`.
> 
> Fine with me. Wasn't done very consistently so far... Should do on any new feature...

Yes, good point! Some of those steady-state computation features should definitively have been released as minor release rather than a patch. We should probably discuss what we consider "new functionality", but let's try to be more consistent in the future.

**Comment by dweindl** [comment]
> Yes, good point! Some of those steady-state computation features should definitively have been released as minor release rather than a patch. We should probably discuss what we consider "new functionality", but let's try to be more consistent in the future.

Yes. I'd say new functionality is anything that is not clearly only a bug fix (without API change). We don't need to worry about running out of version numbers...

**Review by FFroehlich — APPROVED** [review]

**Pull request merged**
