### PR TITLE
Use SymPy simple floating-point optimizations

### PR DESCRIPTION
**Pull request by lcontento**
SymPy offers some simple floating-point optimizations, mainly `exp(1-x) -> expm1(x)` and `log(1+x) -> log1p(x)`. Using them by default should not break anything as far as I can see. Only downside should be an increase in code generation time.

### CODE REVIEW

**Comment by dweindl** [comment]
> Only downside should be an increase in code generation time.

@lcontento , did you test that with any larger model? Would be good to have a rough idea.

**Comment by lcontento** [comment]
> > Only downside should be an increase in code generation time.
> 
> @lcontento , did you test that with any larger model? Would be good to have a rough idea.

I did only test with the KoCo19 coronavirus model which is not small but probably not large either. Is there any model that you would consider large in the PEtab collection? If so I can try and benchmark the change.

**Comment by dweindl** [comment]
I'd go for https://github.com/ICB-DCM/CS_Signalling_ERBB_RAS_AKT:

```
amici_import_petab -v \
            -n 'CS_Signalling_ERBB_RAS_AKT_petab' \
            -y 'FroehlichKes2018/PEtab/FroehlichKes2018.yaml' \
            --no-compile
```

**Comment by lcontento** [comment]
I get the following results
```
                                          w/o opt      w/ opt
Finished computing xdot                 (1.73E+00s) (1.77E+00s)
Finished computing dxdotdx              (7.32E+00s) (7.54E+00s)
Finished computing w                    (7.09E+01s) (7.01E+01s)
Finished computing dwdx                 (1.55E+02s) (1.50E+02s)
Finished computing dwdtcl               (1.16E+01s) (1.11E+01s)
Finished computing dtcldx               (7.74E-01s) (7.60E-01s)
Finished computing dwdx                 (1.76E+02s) (1.71E+02s)
Finished computing J                    (2.14E+02s) (2.09E+02s)
Finished writing J.cpp                  (4.03E+02s) (4.29E+02s)
Finished computing JB                   (1.46E+01s) (1.50E+01s)
Finished writing JB.cpp                 (2.06E+02s) (2.35E+02s)
Finished computing JDiag                (1.40E+00s) (1.64E+00s)
Finished writing JDiag.cpp              (3.04E+01s) (4.15E+01s)
Finished computing JSparse              (6.71E+00s) (6.96E+00s)
Finished writing JSparse.cpp            (2.00E+02s) (2.29E+02s)
Finished computing JSparseB             (6.24E+00s) (6.36E+00s)
Finished writing JSparseB.cpp           (1.98E+02s) (2.29E+02s)
Finished computing Jy                   (6.43E-03s) (6.25E-03s)
Finished writing Jy.cpp                 (3.21E-02s) (6.14E-02s)
Finished computing dJydsigmay           (7.61E-03s) (7.13E-03s)
Finished writing dJydsigmay.cpp         (3.31E-02s) (4.21E-02s)
Finished computing dJydy                (5.01E-03s) (4.67E-03s)
Finished writing dJydy.cpp              (3.01E-02s) (3.56E-02s)
Finished computing dwdp                 (2.86E+02s) (2.85E+02s)
Finished computing dwdp                 (3.14E+02s) (3.13E+02s)
Finished writing dwdp.cpp               (4.63E+02s) (4.67E+02s)
Finished writing dwdx.cpp               (1.20E+02s) (1.33E+02s)
Finished writing dxdotdw.cpp            (1.24E+02s) (1.27E+02s)
Finished computing dxdotdp_explicit     (2.06E+01s) (2.07E+01s)
Finished writing dxdotdp_explicit.cpp   (4.30E+01s) (4.31E+01s)
Finished computing dxdotdp_implicit     (1.06E+01s) (1.07E+01s)
Finished computing y                    (1.25E-02s) (1.28E-02s)
Finished computing dydx                 (1.54E-01s) (1.54E-01s)
Finished computing dydw                 (1.25E-02s) (1.38E-02s)
Finished computing dydx                 (2.21E-01s) (2.23E-01s)
Finished writing dydx.cpp               (5.94E-01s) (7.69E-01s)
Finished computing dydp                 (3.40E-01s) (3.29E-01s)
Finished computing dydp                 (4.00E-01s) (3.91E-01s)
Finished writing dydp.cpp               (8.32E-01s) (9.86E-01s)
Finished computing sigmay               (5.07E-05s) (5.34E-05s)
Finished computing dsigmaydp            (8.87E-02s) (8.24E-02s)
Finished writing dsigmaydp.cpp          (1.45E-01s) (1.42E-01s)
Finished writing sigmay.cpp             (2.30E-02s) (2.45E-02s)
Finished writing w.cpp                  (6.47E+01s) (7.75E+01s)
Finished computing x0                   (1.47E-01s) (1.57E-01s)
Finished writing x0.cpp                 (3.97E+00s) (4.88E+00s)
Finished computing x0_fixedParameters   (9.12E-01s) (9.17E-01s)
Finished writing x0_fixedParameters.cpp (4.71E+00s) (5.63E+00s)
Finished computing sx0                  (1.27E+02s) (1.21E+02s)
Finished writing sx0.cpp                (1.37E+02s) (1.32E+02s)
Finished computing sx0_fixedParameters  (2.14E+01s) (2.00E+01s)
```
Not much difference between the two cases I would say, considering also that the `computing` steps in general take slightly longer in the fp-optimized case (possibly a different background load on my machine?).

Note: in both cases I was not able to reach the end of the program (I killed it after 7 hours with no more timings printed). Not sure if it is expected to take a crazy amount of time or if it is a problem with my out-of-date AMICI fork...

**Comment by lcontento** [comment]
By the way, the signature `_print_with_exception(math: sp.Expr)` does not appear to be respected, since in the CI testing there are cases where `math` is a `list`. If it is a `list` is it going to always be a 1D `list` of numbers? Of what other types could `math` be?

**Comment by dweindl** [comment]
> I get the following results
> [...]

Thanks for comparing. Looks good to me.

> Note: in both cases I was not able to reach the end of the program (I killed it after 7 hours with no more timings printed). Not sure if it is expected to take a crazy amount of time or if it is a problem with my out-of-date AMICI fork...

Hm, yeah, probably a bad version of AMICI. This should succeed in about 30min.

**Comment by dweindl** [comment]
> By the way, the signature `_print_with_exception(math: sp.Expr)` does not appear to be respected, since in the CI testing there are cases where `math` is a `list`. If it is a `list` is it going to always be a 1D `list` of numbers? Of what other types could `math` be?

You are right. Where it currently fails (and on the following line), a list of floats is passed. Not aware of anything else going into `_print_with_exception`.

**Comment by lcontento** [comment]
> > By the way, the signature `_print_with_exception(math: sp.Expr)` does not appear to be respected, since in the CI testing there are cases where `math` is a `list`. If it is a `list` is it going to always be a 1D `list` of numbers? Of what other types could `math` be?
> 
> You are right. Where it currently fails (and on the following line), a list of floats is passed. Not aware of anything else going into `_print_with_exception`.

Another test that fails is due to symbols given as strings. It may be that these situations only occur in test cases where shortcuts are used for brevity/clarity, while in real world usage the `ode_export` machinery takes care of doing `sympification` before calling `_print_with_exception`.

**Comment by dweindl** [comment]
> Another test that fails is due to symbols given as strings. It may be that these situations only occur in test cases where shortcuts are used for brevity/clarity, while in real world usage the `ode_export` machinery takes care of doing `sympification` before calling `_print_with_exception`.

Okay, those tests need to be changed then to pass the proper expressions. Will you look into that?

**Comment by lcontento** [comment]
> > Another test that fails is due to symbols given as strings. It may be that these situations only occur in test cases where shortcuts are used for brevity/clarity, while in real world usage the `ode_export` machinery takes care of doing `sympification` before calling `_print_with_exception`.
> 
> Okay, those tests need to be changed then to pass the proper expressions. Will you look into that?

Ok, I will try to clean this up. I won't put too much priority on this so it may take a while. In the meantime I will change the PR status to draft.

**Comment by dweindl** [comment]
*ping* @lcontento

**Comment by dweindl** [comment]
> Another test that fails is due to symbols given as strings.

I think this is related to #1061

**Pull request merged**
